### ISSUE TITLE
Cannot reload page by URLS

### ISSUE THREAD

**Issue by nguoianphu** [thenaim/ionic-tk-social-network#23]
@thenaim, reload the pages and get 404 error. Examples:
- https://thenaim.github.io/ionic-tk-social-network/tabs/messages
- https://thenaim.github.io/ionic-tk-social-network/tabs/main

I got same issue when run the site in subfolder. Bbut I can fix it by React HashRouter. I don't know how to fix it in Angular. Check my site https://nguoianphu.github.io/pkmn.help/#/pokedex

**Comment by thenaim** [comment]
@nguoianphu, I know about this error, but I don’t know how to solve it yet, so I’m looking for a solution. Thanks for noticing. 

If there are any solutions or ideas, I will be glad. Your project uses the URL fragment instead of the history API. I think this is why the page reload works.

**Comment by thenaim** [comment]
@nguoianphu, good news) Check pages.
